const path = '../assets/accessories/';

export const accessoryImages = {
  'beanie': require(`${path}beanie.png`),
  'bracelet': require(`${path}bracelet.png`),
  'earrings': require(`${path}earrings.png`),
  'glasses': require(`${path}glasses.png`),
  'gloves': require(`${path}gloves.png`),
  'hairTie': require(`${path}hairTie.png`),
  'hairUp': require(`${path}hairUp.png`),
  'hat': require(`${path}hat.png`),
  'cap': require(`${path}cap.png`),
  'hatTight': require(`${path}hatTight.png`),
  'hatWool': require(`${path}hatWool.png`),
  'headscarfhaircontrol': require(`${path}headscarfhaircontrol.png`),
  'necklace': require(`${path}necklace.png`),
  'scarf': require(`${path}scarf.png`),
  'scarfDecorative': require(`${path}scarfDecorative.png`),
  'scarfLight': require(`${path}scarfLight.png`),
  'scarfMedium': require(`${path}scarfMedium.png`),
  'scarfNeck': require(`${path}scarfNeck.png`),
  'scarfThick': require(`${path}scarfThick.png`),
  'sunglasses': require(`${path}sunglasses.png`),
  'watch': require(`${path}watch.png`),
  'waterBottle': require(`${path}waterBottle.png`),
  'rain_boots': require(`${path}rain_boots.png`),
  'raincoat': require(`${path}raincoat.png`),
  'scarfHead': require(`${path}scarfHead.png`),
  'umbrella': require(`${path}umbrella.png`),
  'windbreaker': require(`${path}windbreaker.png`),
  'hair_control': require(`${path}hair_control.png`),
  'simpleNecklace': require(`${path}simpleNecklace.png`)
};
