
export const accessoryImages = {
  // ☀️ Calor
  'sunglasses': require('../assets/images/acessorios/calor/sunglasses.png'),
  'cap': require('../assets/images/acessorios/calor/cap.png'),
  'sunscreen': require('../assets/images/acessorios/calor/sunscreen.png'),

  // ❄️ Frio
  'scarf': require('../assets/images/acessorios/frio/scarf.png'),
  'gloves': require('../assets/images/acessorios/frio/gloves.png'),
  'hat': require('../assets/images/acessorios/frio/hat.png'),

  // ☔ Chuva
  'umbrella': require('../assets/images/acessorios/chuva/umbrella.png'),
  'raincoat': require('../assets/images/acessorios/chuva/raincoat.png'),
  'rain_boots': require('../assets/images/acessorios/chuva/boot.png'),

  // 💨 Vento
  'windbreaker': require('../assets/images/acessorios/vento/windbreaker.png'),
  'beanie': require('../assets/images/acessorios/vento/beanie.png'),
  'hair_elastic': require('../assets/images/acessorios/vento/hairtie.png'),

  'scarfThick': require('../assets/images/acessorios/frio/scarf.png'),
  'hatTight': require('../assets/images/acessorios/frio/gloves.png'),
  'lightGlooves': require('../assets/images/acessorios/frio/hat.png'),

  'bracelet': '',
  'braceletLight': '',
  'braceletNeutral': '',
  'braceletSimple': '',
  'brincoLeve': '',
  'colarSimples': '',
  'earringSimple': '',
  'earrings': '',
  'earringsLight': '',
  'functionalAccessory': '',
  'glasses': '',
  'hairTie': '',
  'hairUp': '',
  'hairUpLong': '',
  'hair_control': '',
  'hatBasic': '',
  'hatFitted': '',
  'hatLight': '',
  'hatOrCap': '',
  'hatWool': '',
  'headscarfhaircontrol': '',
  'lencoNaCabecaSeVento': '',
  'lightGloves': '',
  'necklace': '',
  'necklaceLight': '',
  'necklaceSimple': '',
  'necklaceSport': '',
  'noHat': '',
  'ponytail': '',
  'raincoat_windproof': '',
  'scarfDecorative': '',
  'scarfHeadControl': '',
  'scarfLight': '',
  'scarfMedium': '',
  'scarfNeck': '',
  'scarfNeckLight': '',
  'sunglassesIfSun': '',
  'watch': '',
  'watchSimple': '',
  'waterBottle': '',
};