import { Dimensions, StyleSheet } from 'react-native';
import { theme } from './theme';

const screenWidth = Dimensions.get('window').width;
const cardSpacing = 12;
const containerPadding = 24;
const cardWidth = (screenWidth - containerPadding * 2 - cardSpacing * 2) / 3;

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
    padding: theme.spacing.lg,
    paddingTop: theme.spacing.xl, // ✅ ajuste aplicado para SafeArea
  },
  centered: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  imageWelcome: {
    width: 200,
    height: 200,
    marginTop: theme.spacing.xl,
    marginBottom: theme.spacing.md,
    resizeMode: 'contain',
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  titleWelcome: {
    fontSize: theme.fontSize.extralarge,
    fontWeight: '600',
    fontFamily: 'System',
    color: theme.colors.textDark,
    textAlign: 'center',
    marginBottom: theme.spacing.sm,
    letterSpacing: 0.3,
    lineHeight: 36,
  },
  subtitleWelcome: {
    fontSize: theme.fontSize.medium,
    fontWeight: '400',
    fontFamily: 'System',
    color: theme.colors.textMedium,
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: theme.spacing.lg,
    maxWidth: 280,
    alignSelf: 'center',
    letterSpacing: 0.2,
  },
  subtitleWelcomeStrong: {
    color: theme.colors.textMedium,
    fontWeight: '600',
    fontStyle: 'italic',
  },
  descriptionWithSpacing: {
    color: theme.colors.textMedium,
    fontSize: theme.fontSize.medium,
    marginBottom: theme.spacing.md,
  },
  title: {
    fontSize: theme.fontSize.large,
    fontWeight: '700',
    fontFamily: 'serif',
    color: theme.colors.textDark,
    textAlign: 'left',
    marginBottom: theme.spacing.md,
    letterSpacing: 0.5,
  },
  subtitle: {
    fontSize: theme.fontSize.medium,
    fontWeight: '300',
    color: theme.colors.textLight,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: theme.spacing.lg,
    maxWidth: 280,
    alignSelf: 'center',
    opacity: 11,
  },
  description: {
    color: theme.colors.textDark,
    fontSize: theme.fontSize.medium,
    marginBottom: theme.spacing.sm,
  },
  subtext: {
    fontSize: 12,
    color: theme.colors.textLight,
    marginBottom: theme.spacing.xs,
    fontStyle: 'italic',
  },
  input: {
    borderWidth: 3,
    borderColor: '#ccc',
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
    fontSize: theme.fontSize.medium,
    marginBottom: theme.spacing.lg,
    color: theme.colors.textDark,
  },
  inputFocused: {
    borderColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.35,
    shadowRadius: 6,
    elevation: 3,
  },
  section: {
    marginBottom: theme.spacing.xxl,
  },
  sectionTitle: {
    marginBottom: theme.spacing.sm,
    fontSize: theme.fontSize.medium,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  optionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.lg,
    columnGap: theme.spacing.sm,
    rowGap: theme.spacing.sm,
    flexWrap: 'wrap',
  },
  card: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: theme.radius.md,
    paddingVertical: theme.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    gap: theme.spacing.xs,
    backgroundColor: '#fff',
  },
  cardText: {
    fontSize: theme.fontSize.medium,
    color: theme.colors.textDark,
  },
  block: {
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: theme.radius.md,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    backgroundColor: '#fff',
  },
  blockLabel: {
    fontWeight: 'bold',
    fontSize: theme.fontSize.medium,
    color: theme.colors.textDark,
  },
  blockDesc: {
    fontSize: 12,
    color: theme.colors.textLight,
    marginTop: 4,
  },
  subtextRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: theme.spacing.md,
  },
  subtextItalic: {
    fontSize: 12,
    color: theme.colors.textLight,
    fontStyle: 'italic',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  blockHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    position: 'relative',
    zIndex: 1,
  },
  homeTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  locationBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    padding: 12,
    borderRadius: 12,
    marginBottom: 20,
    gap: 8,
  },
  locationText: {
    fontSize: 16,
    color: theme.colors.textDark,
    flex: 1,
  },
  changeButton: {
    backgroundColor: '#e0ecf8',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  changeButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  cardhome: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    elevation: 2,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 12,
    color: theme.colors.textDark,
  },
  weatherRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  weatherMain: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  weatherSecondary: {
    fontSize: 14,
    color: theme.colors.textLight,
  },
  weatherLabel: {
    marginTop: 4,
    fontSize: 12,
    color: theme.colors.textLight,
  },
  weatherInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    gap: 6,
  },
  weatherInfo: {
    fontSize: 13,
    color: theme.colors.textLight,
    flex: 1,
  },
  lookRow: {
    flexDirection: 'row',
    gap: 12,
    alignItems: 'center',
    marginBottom: 12,
  },
  avatar: {
    width: screenWidth * 0.6,
    height: screenWidth * 0.9,
    resizeMode: 'contain',
  },
  lookText: {
    flex: 1,
    fontSize: 14,
    color: theme.colors.textDark,
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tag: {
    backgroundColor: '#e7f0ff',
    borderRadius: 20,
    paddingVertical: 4,
    paddingHorizontal: 12,
  },
  tagText: {
    fontSize: 12,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  climateInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 40,
  },
  climateInfoWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    gap: 10,
  },
  climateCard: {
    flex: 1,
    backgroundColor: '#f3f9ff',
    borderRadius: 12,
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  climateLabel: {
    fontSize: 13,
    color: theme.colors.textDark,
    marginTop: 2,
  },
  climateValue: {
    fontSize: 15,
    fontWeight: 'bold',
    color: theme.colors.textDark,
    marginTop: 2,
  },
  forecastHeader: {
    backgroundColor: '#a3d5ff',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    gap: 4,
  },
  forecastHeaderCity: {
    fontSize: 16,
    fontWeight: 'bold',
    color: theme.colors.textDark,
    marginTop: 4,
  },
  forecastHeaderDate: {
    fontSize: 13,
    color: theme.colors.textLight,
  },
  forecastMainTemp: {
    fontSize: 32,
    fontWeight: 'bold',
    color: theme.colors.textDark,
  },
  forecastWeatherLabel: {
    fontSize: 14,
    color: theme.colors.textDark,
  },
  hourlyRow: {
  flexDirection: 'row',
  gap: 8,
},
hourCard: {
  width: 70,
  height: 100,
  alignItems: 'center',
  justifyContent: 'center',
  borderRadius: 12,
  backgroundColor: '#fff',
  padding: 8,
},
  hourLabel: {
    fontSize: 13,
    fontWeight: 'bold',
    marginBottom: 4,
    color: theme.colors.textDark,
  },
  hourTemp: {
    fontSize: 14,
    color: theme.colors.textDark,
    marginTop: 4,
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 100,
  },
  detailCard: {
    width: '47%',
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  detailCardFull: {
    width: '100%',
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  detailTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 8,
    marginBottom: 4,
    color: theme.colors.textDark,
  },
  detailValue: {
    fontSize: 13,
    color: theme.colors.textLight,
    lineHeight: 18,
  },
  bottomButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#FFD23F',
    borderRadius: 30,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  bottomButtonText: {
    fontWeight: 'bold',
    color: theme.colors.textDark,
    fontSize: 14,
  },
  overlay: {
    flex: 1,
    backgroundColor: '#00000088',
  },
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    width: '100%',
    backgroundColor: theme.colors.background,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 20,
    maxHeight: '70%',
  },
  searchInput: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    borderRadius: 8,
    marginBottom: 12,
    color: theme.colors.textDark,
  },
  cityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 10,
  },
  cityName: {
    fontSize: 16,
    color: theme.colors.textDark,
  },
  appTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: theme.colors.primary,
    marginBottom: 12,
  },
  heroImage: {
    width: 250,
    height: 250,
    marginBottom: 20,
  },
  button: {
    backgroundColor: theme.colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 28,
    borderRadius: 10,
    elevation: 4,
  },
  buttonPressed: {
    opacity: 0.8,
    transform: [{ scale: 0.98 }],
  },
  buttonText: {
    color: theme.colors.white,
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  suggestionWrapper: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 16,
  },
  accessoryColumn: {
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  accessoryTitle: {
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 8,
  },
  accessoryIconWrapper: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 8,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  accessoryIcon: {
    width: 48,
    height: 48,
  },
  loadingText: {
    fontSize: 16,
    color: '#4a4a4a',
    textAlign: 'center',
    marginTop: 40,
    paddingHorizontal: 20,
    lineHeight: 24,
  },

  // ✅ AJUSTES FINAIS PARA RESPONSIVIDADE DOS BOTÕES DE GÊNERO
  preferenceCardContainer: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.lg,
  },

  preferenceCard: {
    flexGrow: 1,
    flexBasis: '33%',
    maxWidth: '33%',
    paddingVertical: screenWidth < 390 ? 10 : 14,
    paddingHorizontal: 4,
    minHeight: screenWidth < 390 ? 52 : 60,
    borderRadius: theme.radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.border,
    marginHorizontal: 4,
  },

  preferenceCardText: {
    fontSize: screenWidth < 390 ? 13 : 15,
    color: theme.colors.textDark,
    textAlign: 'center',
  },

  preferenceCardIcon: {
    fontSize: screenWidth < 390 ? 18 : 22,
    color: theme.colors.textMedium,
    marginBottom: 4,
  },
});
